name: CI Network Check, Linting, and Docker Build

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run ShellCheck Linter
        uses: ludeeus/action-shellcheck@master

      - name: Make Scripts Executable
        run: chmod +x *.sh

      - name: Run Database Connection Test
        env:
          DATABASE_USER: "admin_app"
          DATABASE_PASS: ${{ secrets.DB_PASSWORD }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: ./database_connect.sh

      - name: Build Docker Image
        run: docker build -t devops-lab-app:latest .
