name: CI Network Check and Linting

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run ShellCheck Linter
        uses: ludeeus/action-shellcheck@master

      - name: Make Script Executable
        run: chmod +x check_network.sh

      - name: Run Network Check Script
        run: ./check_network.sh
